const assert = require('node:assert/strict');
const test = require('node:test');

const {
  applyLocalAndroidBuildProperties,
  upsertGradleProperty,
} = require('./with-local-android-build-properties');

test('upserts a Gradle property without duplicating an existing key', () => {
  const properties = [
    { type: 'property', key: 'newArchEnabled', value: 'true' },
    { type: 'property', key: 'reactNativeArchitectures', value: 'x86' },
  ];

  upsertGradleProperty(properties, 'reactNativeArchitectures', 'arm64-v8a');

  assert.deepEqual(properties, [
    { type: 'property', key: 'newArchEnabled', value: 'true' },
    { type: 'property', key: 'reactNativeArchitectures', value: 'arm64-v8a' },
  ]);
});

test('adds a Gradle property when the key is missing', () => {
  const properties = [{ type: 'comment', value: 'Generated by Expo' }];

  upsertGradleProperty(properties, 'org.gradle.workers.max', '2');

  assert.deepEqual(properties, [
    { type: 'comment', value: 'Generated by Expo' },
    { type: 'property', key: 'org.gradle.workers.max', value: '2' },
  ]);
});

test('applies the Android minSdk required by native pose inference', () => {
  const properties = [
    { type: 'property', key: 'android.minSdkVersion', value: '24' },
  ];

  applyLocalAndroidBuildProperties(properties, {
    minSdkVersion: '26',
  });

  assert.deepEqual(properties, [
    { type: 'property', key: 'android.minSdkVersion', value: '26' },
  ]);
});
