#!/usr/bin/env bash
# Pull the canonical Shinsa jacket pack from prod into mobile/assets/jackets/
# and regenerate mobile/lib/jacket-manifest.ts so the Metro bundler ships
# them with the APK / Expo bundle.
#
# Run this before each release build so newly catalogued songs land in
# the local cache. The .gitignore excludes both the assets and the
# manifest — they're machine-generated.
#
# Usage:
#   ./scripts/sync-jackets.sh
#
# Source: /opt/Shinsa/client/public/jackets/pump/*.jpg on prod (the same
# folder nginx serves at https://pumpshinsa.com/jackets/pump/*.jpg).
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
MOBILE_DIR=$(cd "$SCRIPT_DIR/.." && pwd)
DEST_DIR="$MOBILE_DIR/assets/jackets/pump"
MANIFEST="$MOBILE_DIR/lib/jacket-manifest.ts"
SERVER="root@159.65.91.103"
REMOTE_DIR="/opt/Shinsa/client/public/jackets/pump"

mkdir -p "$DEST_DIR"

echo "→ rsyncing jackets from $SERVER:$REMOTE_DIR"
rsync -az --delete "$SERVER:$REMOTE_DIR/" "$DEST_DIR/"

COUNT=$(find "$DEST_DIR" -maxdepth 1 -name '*.jpg' -o -name '*.png' | wc -l | tr -d ' ')
SIZE=$(du -sh "$DEST_DIR" | awk '{print $1}')
echo "→ synced $COUNT jackets ($SIZE total)"

echo "→ regenerating $MANIFEST"
MOBILE_DIR="$MOBILE_DIR" node - <<'NODE'
const fs = require('fs');
const path = require('path');

const mobileDir = process.env.MOBILE_DIR;
if (!mobileDir) throw new Error('MOBILE_DIR env var missing');
const jacketsDir = path.join(mobileDir, 'assets/jackets/pump');
const manifestPath = path.join(mobileDir, 'lib/jacket-manifest.ts');

const files = fs
  .readdirSync(jacketsDir)
  .filter((name) => /\.(jpg|jpeg|png|webp)$/i.test(name))
  .sort();

const lines = files.map((name) => {
  // The asset paths use Metro's require resolver — relative paths from
  // the manifest file. Both jpg and png are bundled into the APK as-is.
  const urlPath = `/jackets/pump/${name}`;
  return `  ${JSON.stringify(urlPath)}: require('../assets/jackets/pump/${name}'),`;
});

const body = `/* eslint-disable */
// AUTO-GENERATED by scripts/sync-jackets.sh. DO NOT EDIT BY HAND.
// Maps each Shinsa-hosted jacket URL path to the bundled asset module id.
// At runtime, the resolver in lib/jacket.ts looks the URL up here and
// returns the local require() so Image renders from the APK instead of
// hitting the network.
// Generated: ${new Date().toISOString()}
// Source: /opt/Shinsa/client/public/jackets/pump
// Count: ${files.length}

const JACKET_MANIFEST: Record<string, number> = {
${lines.join('\n')}
};

export default JACKET_MANIFEST;
`;

fs.writeFileSync(manifestPath, body);
console.log(`→ wrote ${files.length} entries to ${path.relative(process.cwd(), manifestPath)}`);
NODE

echo
echo "Done. Restart Metro / rebuild the APK to pick up new jackets."
