const { parseUtcSqliteDateTime } = require('./liveSessionSummary');
const { parsePiugamePlayedAtUtc } = require('./piugameDate');
const { gradeFromScore, normalizeGrade } = require('./titleProgress');

const SHINSA_CHAPTERS_HEADER = 'Chapters generated by SHINSA';
const SHINSA_CHAPTERS_FOOTER = 'End SHINSA chapters';
const SHINSA_CHAPTERS_BLOCK_REGEX = /(?:^|\n)Chapters generated by SHINSA\n[\s\S]*?\nEnd SHINSA chapters(?:\n|$)/i;

function toInt(value) {
  return parseInt(value, 10) || 0;
}

function parseUtcLike(value) {
  const raw = String(value || '').trim();
  if (!raw) return null;
  if (/[zZ]$/.test(raw) || /[+-]\d{2}:\d{2}$/.test(raw) || /[+-]\d{4}$/.test(raw)) {
    const direct = new Date(raw);
    return Number.isNaN(direct.getTime()) ? null : direct;
  }
  return parseUtcSqliteDateTime(raw) || null;
}

function parsePlayEndedAt(play) {
  return (
    parsePiugamePlayedAtUtc(play?.date_played)
    || parseUtcSqliteDateTime(play?.played_at_utc)
    || null
  );
}

function formatChapterOffset(totalSeconds) {
  const safeSeconds = Math.max(0, toInt(totalSeconds));
  const hours = Math.floor(safeSeconds / 3600);
  const minutes = Math.floor((safeSeconds % 3600) / 60);
  const seconds = safeSeconds % 60;
  if (hours > 0) {
    return `${hours}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
  }
  return `${minutes}:${String(seconds).padStart(2, '0')}`;
}

function formatScore(value) {
  const score = Math.max(0, toInt(value));
  return score > 0 ? score.toLocaleString('en-US') : '';
}

function resolvePlayGrade(play) {
  const normalized = normalizeGrade(play?.grade || '');
  if (normalized) return normalized;
  const score = toInt(play?.score);
  return score > 0 ? gradeFromScore(score) : '';
}

function formatChapterResult(play) {
  const grade = resolvePlayGrade(play);
  const scoreLabel = formatScore(play?.score);
  if (!grade && !scoreLabel) return '';
  if (!grade) return scoreLabel;
  if (!scoreLabel) return grade;
  return `${grade} ${scoreLabel}`;
}

function isPassingPlay(play) {
  const score = toInt(play?.score);
  if (score <= 0) return false;
  return resolvePlayGrade(play) !== 'F';
}

function formatChapterLabel(play) {
  const title = String(play?.song_title || '').trim() || 'Unknown song';
  const mode = String(play?.mode || '').trim();
  const level = toInt(play?.level);
  const suffix = mode && level > 0
    ? ` (${mode === 'Single' ? 'S' : mode === 'Double' ? 'D' : mode.slice(0, 1).toUpperCase()}${level})`
    : '';
  const result = formatChapterResult(play);
  return `${title}${suffix}${result ? ` ${result}` : ''}`;
}

function sanitizeChapterTitle(title, fallbackIndex) {
  const trimmed = String(title || '').replace(/\s+/g, ' ').trim();
  if (!trimmed) return `Song ${fallbackIndex}`;
  return trimmed.slice(0, 100);
}

function buildManagedYoutubeChaptersBlock(text) {
  const normalizedText = String(text || '').trim();
  return [
    SHINSA_CHAPTERS_HEADER,
    normalizedText,
    SHINSA_CHAPTERS_FOOTER,
  ].join('\n');
}

function upsertManagedYoutubeChaptersBlock(description, text) {
  const baseDescription = String(description || '').trim();
  const block = buildManagedYoutubeChaptersBlock(text);
  if (!baseDescription) return block;
  if (SHINSA_CHAPTERS_BLOCK_REGEX.test(baseDescription)) {
    return baseDescription.replace(SHINSA_CHAPTERS_BLOCK_REGEX, `\n${block}\n`).trim();
  }
  return `${baseDescription}\n\n${block}`.trim();
}

function stripManagedYoutubeChaptersBlock(description) {
  return String(description || '').replace(SHINSA_CHAPTERS_BLOCK_REGEX, '\n').replace(/\n{3,}/g, '\n\n').trim();
}

function buildYoutubeTimestampPayload(session, plays = [], video = null) {
  const videoActualStart = parseUtcLike(video?.actual_start_time);
  const sessionActualStart = parseUtcLike(session?.youtube_actual_start_time);
  const videoScheduledStart = parseUtcLike(video?.scheduled_start_time);
  const sessionScheduledStart = parseUtcLike(session?.youtube_scheduled_start_time);
  const sessionStartedAt = parseUtcSqliteDateTime(session?.started_at) || null;
  const sourceStart = (
    videoActualStart
    || sessionActualStart
    || videoScheduledStart
    || sessionScheduledStart
    || sessionStartedAt
    || null
  );
  const sourceStartKind = videoActualStart
    ? 'youtube_video_actual_start_time'
    : sessionActualStart
      ? 'youtube_actual_start_time'
      : videoScheduledStart
        ? 'youtube_video_scheduled_start_time'
        : sessionScheduledStart
          ? 'youtube_scheduled_start_time'
          : sessionStartedAt
            ? 'session_started_at'
            : '';

  if (!sourceStart) {
    const err = new Error('No usable stream start time is available for this session yet');
    err.statusCode = 409;
    throw err;
  }

  const rows = Array.isArray(plays) ? plays : [];
  const enriched = rows
    .map((play) => {
      const endedAt = parsePlayEndedAt(play);
      const durationSeconds = Math.max(0, toInt(play?.duration_seconds));
      if (!endedAt || durationSeconds <= 0) {
        return {
          play,
          endedAt,
          durationSeconds,
          missingDuration: durationSeconds <= 0,
          skipped: true,
          skipReason: durationSeconds <= 0 ? 'missing_duration' : 'missing_end_time',
        };
      }

      const startedAt = new Date(endedAt.getTime() - (durationSeconds * 1000));
      return {
        play,
        endedAt,
        startedAt,
        durationSeconds,
        missingDuration: false,
        skipped: false,
        rawOffsetSeconds: Math.floor((startedAt.getTime() - sourceStart.getTime()) / 1000),
      };
    })
    .sort((a, b) => {
      const aTime = a.startedAt?.getTime() || a.endedAt?.getTime() || 0;
      const bTime = b.startedAt?.getTime() || b.endedAt?.getTime() || 0;
      return aTime - bTime;
    });

  const missingDurations = [];
  const chapters = [
    {
      offset_seconds: 0,
      offset_label: '0:00',
      title: 'Stream start',
      song_title: '',
      mode: '',
      level: 0,
      duration_seconds: 0,
      played_at_utc: '',
      started_at_utc: sourceStart.toISOString(),
    },
  ];

  let previousOffset = 0;
  let matchedCount = 0;
  let skippedNegativeOffsetCount = 0;
  let skippedNonClearCount = 0;

  for (const item of enriched) {
    if (item.missingDuration) {
      missingDurations.push({
        song_title: String(item.play?.song_title || '').trim(),
        mode: String(item.play?.mode || '').trim(),
        level: toInt(item.play?.level),
      });
      continue;
    }
    if (item.skipped || !item.startedAt) continue;
    if (!isPassingPlay(item.play)) {
      skippedNonClearCount += 1;
      continue;
    }

    let nextOffset = Math.max(0, toInt(item.rawOffsetSeconds));
    if (item.rawOffsetSeconds < 0) skippedNegativeOffsetCount += 1;
    if (nextOffset <= previousOffset) {
      nextOffset = previousOffset + 1;
    }
    previousOffset = nextOffset;
    matchedCount += 1;

    chapters.push({
      offset_seconds: nextOffset,
      offset_label: formatChapterOffset(nextOffset),
      title: sanitizeChapterTitle(formatChapterLabel(item.play), chapters.length),
      song_title: String(item.play?.song_title || '').trim(),
      mode: String(item.play?.mode || '').trim(),
      level: toInt(item.play?.level),
      score: toInt(item.play?.score),
      grade: resolvePlayGrade(item.play),
      result_label: formatChapterResult(item.play),
      duration_seconds: item.durationSeconds,
      played_at_utc: String(item.play?.played_at_utc || '').trim(),
      started_at_utc: item.startedAt.toISOString(),
    });
  }

  const text = chapters.map((chapter) => `${chapter.offset_label} ${chapter.title}`.trim()).join('\n');

  return {
    source_start_at: sourceStart.toISOString(),
    source_start_kind: sourceStartKind,
    chapters,
    text,
    matched_count: matchedCount,
    missing_duration_count: missingDurations.length,
    missing_durations: missingDurations,
    skipped_negative_offset_count: skippedNegativeOffsetCount,
    skipped_non_clear_count: skippedNonClearCount,
  };
}

module.exports = {
  SHINSA_CHAPTERS_BLOCK_REGEX,
  SHINSA_CHAPTERS_FOOTER,
  SHINSA_CHAPTERS_HEADER,
  buildManagedYoutubeChaptersBlock,
  buildYoutubeTimestampPayload,
  formatChapterOffset,
  stripManagedYoutubeChaptersBlock,
  upsertManagedYoutubeChaptersBlock,
};
